name: Update Cron Job

on:
  schedule:
    - cron: "*/60 */24 * * *"
  push:
      branches:
        - 'main'

jobs:
  cron:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Install python
        run: sudo apt install python3
        
      - name: Install dependencies
        run: git clone https://github.com/Junkiez/CHRONOS.git
        
      - name: Install dependencies
        run: ls
    
      - name: Install dependencies
        run: pip install -r CHRONOS/requirements.txt
        
      - name: Run update script
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
        run: python CHRONOS/main.py 
