  # This is a basic workflow to help you get started with Actions

name: First Cron Job

       # Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Install python
        run: sudo apt install python3
        
      - name: Install dependencies
        run: git clone https://github.com/Junkiez/CHRONOS.git
        
      - name: Install dependencies
        run: cd CHRONOS
    
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run update script
        run: python main.py
