name: Update Cron Job

on:
  schedule:
    - cron: "*/60 */24 * * *"
  push:
      branches:
        - 'main'

jobs:
  cron:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Use repo
        uses: actions/checkout@v3
    
      - name: Install python
        run: sudo apt install python3
    
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run update script
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
        run: python main.py 
